services:
  - type: web
    name: aurelian-backend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: MIDTRANS_SERVER_KEY
        sync: false
      - key: MIDTRANS_CLIENT_KEY
        sync: false
      - key: MIDTRANS_MERCHANT_ID
        sync: false
